function perfData = setUpPerfData()
perfData.eyelidpos=[];
perfData.hitIdx=[];
perfData.hitIdx2=[];
perfData.missIdx=[];
perfData.missIdx2=[];
perfData.encoder_displacement = [];
perfData.c_isi = [];
perfData.c_csnum = [];
perfData.c_csdur = [];
perfData.c_usnum = [];
perfData.c_usdur = [];
perfData.type = [];
perfData.tDay = [];
perfData.date = [];
perfData.laserDur = [];
perfData.mouse = [];
perfData.FEC180=[];
perfData.baseline=[];
perfData.URAmp = [];
perfData.URInt = [];
perfData.baselineMvt = [];
perfData.cradjamp = [];
perfData.phase = [];
perfData.peakval = [];
perfData.peaktm = [];
perfData.group = [];
end